// Accounting Suite v7 — migration, contacts, AP, close, tax, audit, backup, basic ledger
// Adds new Google Sheet tabs only. Existing expense/income data and schemas are never overwritten.

import { getAccessToken } from "./google-auth.js";
import { normalizeDate, readExpenses, readSettings } from "./sheets.js";
import { listIncome, listIncomePayments, listIncomeReconciliationRows, createIncome } from "./income.js";
import { getReconciliationDashboard } from "./reconciliation.js";

const SHEETS="https://sheets.googleapis.com/v4/spreadsheets";
export const ACCOUNTING_SUITE_VERSION="ACCOUNTING_SUITE_V7_20260809";

export const TABS={
  contacts:"คู่ค้า",
  ap:"เจ้าหนี้",
  apPayments:"จ่ายเจ้าหนี้",
  opening:"ยอดยกมา",
  periods:"ปิดงวด",
  audit:"_audit_log",
  archive:"ประวัติเดิม",
  migration:"_migration_log",
  coa:"ผังบัญชี",
  journal:"สมุดรายวัน",
};

const CONTACT_SCHEMA=[
 ["A","id","contact_id"],["B","type","ประเภทคู่ค้า"],["C","name","ชื่อคู่ค้า"],["D","taxId","เลขผู้เสียภาษี"],["E","branch","สาขา"],["F","email","อีเมล"],["G","phone","โทรศัพท์"],["H","address","ที่อยู่"],["I","paymentTerms","เครดิตเทอม (วัน)"],["J","defaultWhtRate","WHT เริ่มต้น %"],["K","vatRegistered","จด VAT"],["L","active","ใช้งาน"],["M","source","แหล่งที่มา"],["N","createdAt","สร้างเมื่อ"],["O","updatedAt","แก้ไขเมื่อ"]
];
const AP_SCHEMA=[
 ["A","issueDate","วันที่เอกสาร"],["B","dueDate","วันครบกำหนด"],["C","id","ap_id"],["D","supplierId","supplier_id"],["E","supplier","ผู้ขาย/เจ้าหนี้"],["F","supplierTaxId","เลขผู้เสียภาษี"],["G","documentType","ประเภทเอกสาร"],["H","billNo","เลขที่บิล/ใบแจ้งหนี้"],["I","taxInvoiceNo","เลขใบกำกับภาษี"],["J","category","หมวดค่าใช้จ่าย"],["K","description","รายละเอียด"],["L","subtotal","ฐานก่อน VAT"],["M","vatAmount","VAT"],["N","grossAmount","ยอดตามเอกสาร"],["O","whtRate","WHT %"],["P","whtAmount","WHT"],["Q","netPayable","ยอดที่ต้องจ่ายจริง"],["R","paidAmount","จ่ายแล้ว"],["S","settledAmount","ยอดตัดเจ้าหนี้"],["T","outstanding","คงค้าง"],["U","status","สถานะ"],["V","paymentChannelId","ช่องทางจ่ายล่าสุด"],["W","attachmentUrl","เอกสาร/หลักฐาน"],["X","note","หมายเหตุ"],["Y","source","แหล่งที่มา"],["Z","createdAt","สร้างเมื่อ"],["AA","updatedAt","แก้ไขเมื่อ"]
];
const AP_PAY_SCHEMA=[
 ["A","paymentId","payment_id"],["B","apId","ap_id"],["C","paidDate","วันที่จ่าย"],["D","cashAmount","เงินออกจริง"],["E","whtAmount","หัก ณ ที่จ่าย"],["F","settledAmount","ยอดตัดเจ้าหนี้"],["G","paymentChannelId","ช่องทางจ่าย"],["H","referenceNo","เลขอ้างอิง"],["I","slipUrl","หลักฐานโอน"],["J","note","หมายเหตุ"],["K","createdAt","สร้างเมื่อ"]
];
const OPEN_SCHEMA=[
 ["A","asOfDate","วันที่ยอดยกมา"],["B","id","opening_id"],["C","accountCode","รหัสบัญชี"],["D","accountName","ชื่อบัญชี"],["E","debit","เดบิต"],["F","credit","เครดิต"],["G","reference","อ้างอิง"],["H","note","หมายเหตุ"],["I","source","แหล่งที่มา"],["J","createdAt","สร้างเมื่อ"]
];
const PERIOD_SCHEMA=[
 ["A","period","งวด YYYY-MM"],["B","status","สถานะ"],["C","closedAt","ปิดเมื่อ"],["D","closedBy","ปิดโดย"],["E","reopenedAt","เปิดใหม่เมื่อ"],["F","reopenedBy","เปิดใหม่โดย"],["G","reason","เหตุผล"],["H","checklistJson","ผลตรวจตอนปิด"]
];
const AUDIT_SCHEMA=[
 ["A","time","เวลา"],["B","id","audit_id"],["C","actor","ผู้ดำเนินการ"],["D","action","การกระทำ"],["E","entityType","ประเภทข้อมูล"],["F","entityId","รหัสข้อมูล"],["G","summary","สรุป"],["H","beforeJson","ก่อนแก้"],["I","afterJson","หลังแก้"],["J","source","ช่องทาง"]
];
const ARCHIVE_SCHEMA=[
 ["A","transactionDate","วันที่"],["B","id","archive_id"],["C","direction","ทิศทาง"],["D","docNo","เลขเอกสาร"],["E","party","คู่ค้า"],["F","description","รายละเอียด"],["G","amount","ยอด"],["H","vat","VAT"],["I","wht","WHT"],["J","status","สถานะ"],["K","sourceSystem","ระบบเดิม"],["L","sourceRef","อ้างอิงเดิม"],["M","attachmentUrl","ลิงก์เอกสาร"],["N","rawJson","ข้อมูลต้นฉบับ"],["O","importBatchId","migration_batch"],["P","createdAt","นำเข้าเมื่อ"]
];
const MIGRATION_SCHEMA=[
 ["A","importedAt","นำเข้าเมื่อ"],["B","batchId","migration_batch"],["C","type","ประเภทข้อมูล"],["D","fileName","ชื่อไฟล์"],["E","total","จำนวนทั้งหมด"],["F","success","สำเร็จ"],["G","failed","ผิดพลาด"],["H","status","สถานะ"],["I","notes","หมายเหตุ"]
];
const COA_SCHEMA=[
 ["A","code","รหัสบัญชี"],["B","name","ชื่อบัญชี"],["C","type","หมวดบัญชี"],["D","parent","บัญชีแม่"],["E","active","ใช้งาน"],["F","system","บัญชีระบบ"],["G","updatedAt","อัปเดต"]
];
const JOURNAL_SCHEMA=[
 ["A","date","วันที่"],["B","journalId","journal_id"],["C","reference","อ้างอิง"],["D","description","คำอธิบาย"],["E","accountCode","รหัสบัญชี"],["F","accountName","ชื่อบัญชี"],["G","debit","เดบิต"],["H","credit","เครดิต"],["I","sourceType","แหล่งรายการ"],["J","sourceId","source_id"],["K","createdAt","สร้างเมื่อ"],["L","postedBy","บันทึกโดย"]
];

const DEFAULT_COA=[
 ["1000","เงินสดและธนาคาร","สินทรัพย์","","TRUE","TRUE"],
 ["1100","ลูกหนี้การค้า","สินทรัพย์","","TRUE","TRUE"],
 ["1150","ภาษีหัก ณ ที่จ่ายรอรับ","สินทรัพย์","","TRUE","TRUE"],
 ["1190","ภาษีซื้อ","สินทรัพย์","","TRUE","TRUE"],
 ["2000","เจ้าหนี้การค้า","หนี้สิน","","TRUE","TRUE"],
 ["2050","เจ้าหนี้พนักงาน/ค่าใช้จ่ายค้างจ่าย","หนี้สิน","","TRUE","TRUE"],
 ["2150","ภาษีหัก ณ ที่จ่ายค้างจ่าย","หนี้สิน","","TRUE","TRUE"],
 ["2190","ภาษีขาย","หนี้สิน","","TRUE","TRUE"],
 ["3000","ทุนและกำไรสะสม","ส่วนของเจ้าของ","","TRUE","TRUE"],
 ["4000","รายได้จากการขายและบริการ","รายได้","","TRUE","TRUE"],
 ["5000","ค่าใช้จ่ายดำเนินงาน","ค่าใช้จ่าย","","TRUE","TRUE"],
 ["5900","ค่าใช้จ่ายอื่น","ค่าใช้จ่าย","","TRUE","TRUE"],
];

const S={contacts:CONTACT_SCHEMA,ap:AP_SCHEMA,apPayments:AP_PAY_SCHEMA,opening:OPEN_SCHEMA,periods:PERIOD_SCHEMA,audit:AUDIT_SCHEMA,archive:ARCHIVE_SCHEMA,migration:MIGRATION_SCHEMA,coa:COA_SCHEMA,journal:JOURNAL_SCHEMA};
const LAST=Object.fromEntries(Object.entries(S).map(([k,s])=>[k,s.at(-1)[0]]));
const COL=Object.fromEntries(Object.entries(S).map(([k,s])=>[k,Object.fromEntries(s.map(([c,key])=>[key,c]))]));

function id(prefix){return `${prefix}_${crypto.randomUUID().replace(/-/g,"").slice(0,10).toUpperCase()}`;}
function clean(v,n=500){return String(v??"").trim().slice(0,n);}
function num(v){const n=Number(String(v??"").replace(/,/g,""));return Number.isFinite(n)?n:0;}
function round2(v){return Math.round((num(v)+Number.EPSILON)*100)/100;}
function truthy(v){return v===true||["1","true","yes","ใช่","y"].includes(String(v??"").toLowerCase());}
function iso(v){return normalizeDate(v||new Date()).iso;}
function month(v){const d=iso(v);return d.slice(0,7);}
function now(){return new Date().toISOString();}
async function auth(env,token){return token||await getAccessToken(env);}
function range(sheetId,tab,a1,suffix=""){return `${SHEETS}/${sheetId}/values/${encodeURIComponent(`${tab}!${a1}`)}${suffix}`;}
async function call(t,url,opt={}){const r=await fetch(url,{...opt,headers:{Authorization:`Bearer ${t}`,"content-type":"application/json",...(opt.headers||{})}});const text=await r.text();if(!r.ok)throw new Error(`Sheets ${r.status}: ${text.slice(0,350)}`);return text?JSON.parse(text):{};}
async function meta(t,sheetId){return call(t,`${SHEETS}/${sheetId}?fields=sheets.properties`);}
async function ensureTab(t,sheetId,title,schema){
  const m=await meta(t,sheetId);const exists=(m.sheets||[]).some(x=>x.properties?.title===title);
  if(!exists)await call(t,`${SHEETS}/${sheetId}:batchUpdate`,{method:"POST",body:JSON.stringify({requests:[{addSheet:{properties:{title,gridProperties:{frozenRowCount:1}}}}]})});
  const headers=schema.map(([, ,h])=>h);await call(t,range(sheetId,title,`A1:${schema.at(-1)[0]}1`,`?valueInputOption=USER_ENTERED`),{method:"PUT",body:JSON.stringify({values:[headers]})});
  return {tab:title,created:!exists};
}
async function ensureOne(env,sheetId,token,key){const t=await auth(env,token),cacheKey=`accttab:v7:${sheetId}:${key}`;if(env.KV&&await env.KV.get(cacheKey).catch(()=>null)==="1")return {tab:TABS[key],cached:true};const out=await ensureTab(t,sheetId,TABS[key],S[key]);if(env.KV)await env.KV.put(cacheKey,"1",{expirationTtl:86400}).catch(()=>{});return out;}
async function list(env,sheetId,token,key,{reverse=true}={}){const t=await auth(env,token);await ensureOne(env,sheetId,t,key);const d=await call(t,range(sheetId,TABS[key],`A2:${LAST[key]}`));const rows=(d.values||[]).map((v,i)=>rowObj(v,i+2,S[key])).filter(r=>Object.entries(r).some(([k,v])=>k!=="_row"&&String(v??"").trim()));return reverse?rows.reverse():rows;}
function rowObj(v,rowNo,schema){const o={_row:rowNo};schema.forEach(([,k],i)=>o[k]=v?.[i]??"");return o;}
async function append(env,sheetId,token,key,obj){const t=await auth(env,token);await ensureOne(env,sheetId,t,key);const values=S[key].map(([,k])=>obj[k]??"");const d=await call(t,range(sheetId,TABS[key],`A:${LAST[key]}`,":append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS"),{method:"POST",body:JSON.stringify({values:[values]})});return {ok:true,updatedRange:d.updates?.updatedRange||"",record:obj};}
async function appendMany(env,sheetId,token,key,objects=[]){const t=await auth(env,token);if(!objects.length)return {ok:true,count:0};await ensureOne(env,sheetId,t,key);let count=0;for(let i=0;i<objects.length;i+=500){const chunk=objects.slice(i,i+500),values=chunk.map(obj=>S[key].map(([,k])=>obj[k]??""));await call(t,range(sheetId,TABS[key],`A:${LAST[key]}`,":append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS"),{method:"POST",body:JSON.stringify({values})});count+=chunk.length;}return {ok:true,count};}
async function patchRow(env,sheetId,token,key,row,patch){const t=await auth(env,token);const data=[];for(const [k,v] of Object.entries(patch||{})){const c=COL[key][k];if(c)data.push({range:`${TABS[key]}!${c}${row._row}`,values:[[v??""]]});}if(data.length)await call(t,`${SHEETS}/${sheetId}/values:batchUpdate`,{method:"POST",body:JSON.stringify({valueInputOption:"USER_ENTERED",data})});return {...row,...patch};}
async function countRows(env,sheetId,token,key){const t=await auth(env,token);await ensureOne(env,sheetId,t,key);const d=await call(t,range(sheetId,TABS[key],"A2:A"));return (d.values||[]).filter(r=>String(r?.[0]??"").trim()).length;}
async function findBy(env,sheetId,token,key,field,value){return (await list(env,sheetId,token,key)).find(x=>String(x[field]||"")===String(value||""))||null;}

export async function ensureAccountingSuiteTabs(env,sheetId,token=null){
  const t=await auth(env,token),m=await meta(t,sheetId),existing=new Set((m.sheets||[]).map(x=>x.properties?.title));
  const missing=Object.keys(TABS).filter(k=>!existing.has(TABS[k]));
  if(missing.length){
    await call(t,`${SHEETS}/${sheetId}:batchUpdate`,{method:"POST",body:JSON.stringify({requests:missing.map(k=>({addSheet:{properties:{title:TABS[k],gridProperties:{frozenRowCount:1}}}}))})});
  }
  const data=Object.keys(TABS).map(k=>({range:`${TABS[k]}!A1:${LAST[k]}1`,values:[S[k].map(([, ,h])=>h)]}));
  await call(t,`${SHEETS}/${sheetId}/values:batchUpdate`,{method:"POST",body:JSON.stringify({valueInputOption:"USER_ENTERED",data})});
  const coaData=await call(t,range(sheetId,TABS.coa,`A2:${LAST.coa}`)).catch(()=>({values:[]}));
  let seededCoa=0;
  if(!(coaData.values||[]).some(r=>r.some(v=>String(v||"").trim()))){
    const ts=now(),values=DEFAULT_COA.map(r=>[r[0],r[1],r[2],r[3],r[4],r[5],ts]);
    await call(t,range(sheetId,TABS.coa,`A:${LAST.coa}`,":append?valueInputOption=USER_ENTERED&insertDataOption=INSERT_ROWS"),{method:"POST",body:JSON.stringify({values})});
    seededCoa=values.length;
  }
  if(env.KV)for(const k of Object.keys(TABS))await env.KV.put(`accttab:v7:${sheetId}:${k}`,"1",{expirationTtl:86400}).catch(()=>{});
  return {version:ACCOUNTING_SUITE_VERSION,created:missing.map(k=>TABS[k]),seededCoa};
}

export async function writeAudit(env,sheetId,token,{actor="Dashboard",action="UPDATE",entityType="",entityId="",summary="",before=null,after=null,source="Dashboard"}={}){
  try{return await append(env,sheetId,token,"audit",{time:now(),id:id("AUD"),actor:clean(actor,120),action:clean(action,80),entityType:clean(entityType,80),entityId:clean(entityId,120),summary:clean(summary,500),beforeJson:before?JSON.stringify(before).slice(0,45000):"",afterJson:after?JSON.stringify(after).slice(0,45000):"",source:clean(source,80)});}catch(e){console.warn("audit",e.message);return {ok:false,error:e.message};}
}

export async function isPeriodClosed(env,sheetId,date,token=null){const p=month(date);const rows=await list(env,sheetId,token,"periods");const r=rows.find(x=>String(x.period)===p);return r?.status==="ปิดงวด"?r:null;}
export async function assertPeriodOpen(env,sheetId,date,token=null){const r=await isPeriodClosed(env,sheetId,date,token);if(r){const e=new Error(`งวด ${r.period} ถูกปิดบัญชีแล้ว กรุณาเปิดงวดใหม่ก่อนแก้ไขรายการย้อนหลัง`);e.code="PERIOD_LOCKED";e.period=r.period;throw e;}return true;}

export async function getContacts(env,sheetId,token=null){const rows=await list(env,sheetId,token,"contacts");return {ok:true,rows,summary:{total:rows.filter(x=>String(x.active||"TRUE")!=="FALSE").length,customers:rows.filter(x=>/ลูกค้า|ทั้งสอง/.test(x.type)).length,suppliers:rows.filter(x=>/ผู้ขาย|เจ้าหนี้|ทั้งสอง/.test(x.type)).length}};}
export async function upsertContact(env,sheetId,payload={},token=null,actor="Dashboard"){
  const contactId=clean(payload.id||payload.contactId,80),incomingTax=clean(payload.taxId,30),incomingName=clean(payload.name,200);let existing=contactId?await findBy(env,sheetId,token,"contacts","id",contactId):null;if(!existing&&(incomingTax||incomingName)){const rows=await list(env,sheetId,token,"contacts");existing=rows.find(r=>(incomingTax&&String(r.taxId||"").replace(/\D/g,"")===incomingTax.replace(/\D/g,""))||(!incomingTax&&incomingName&&String(r.name||"").trim().toLowerCase()===incomingName.toLowerCase()))||null;}const ts=now(),incomingType=clean(payload.type,30),existingType=clean(existing?.type,30);const mergedType=existingType&&incomingType&&existingType!==incomingType&&!/ทั้งสอง/.test(existingType+incomingType)?"ทั้งสอง":(incomingType||existingType||"ทั้งสอง");
  const rec={id:existing?.id||id("CON"),type:mergedType,name:clean(payload.name||existing?.name,200),taxId:clean(payload.taxId||existing?.taxId,30),branch:clean(payload.branch||existing?.branch||"สำนักงานใหญ่",100),email:clean(payload.email||existing?.email,180),phone:clean(payload.phone||existing?.phone,60),address:clean(payload.address||existing?.address,800),paymentTerms:Math.max(0,Math.min(365,num(payload.paymentTerms??existing?.paymentTerms))),defaultWhtRate:Math.max(0,Math.min(100,num(payload.defaultWhtRate??existing?.defaultWhtRate))),vatRegistered:(payload.vatRegistered??existing?.vatRegistered)===false?"FALSE":"TRUE",active:(payload.active??existing?.active)!==false?"TRUE":"FALSE",source:clean(payload.source||existing?.source||"Dashboard",80),createdAt:existing?.createdAt||ts,updatedAt:ts};
  if(!rec.name)return {ok:false,error:"กรอกชื่อคู่ค้าก่อน"};
  if(existing){const out=await patchRow(env,sheetId,token,"contacts",existing,rec);await writeAudit(env,sheetId,token,{actor,action:"UPDATE_CONTACT",entityType:"contact",entityId:rec.id,summary:`แก้ไขคู่ค้า ${rec.name}`,before:existing,after:out});return {ok:true,record:out};}
  await append(env,sheetId,token,"contacts",rec);await writeAudit(env,sheetId,token,{actor,action:"CREATE_CONTACT",entityType:"contact",entityId:rec.id,summary:`เพิ่มคู่ค้า ${rec.name}`,after:rec});return {ok:true,record:rec};
}

function apStatus(r){const out=round2(r.outstanding);if(String(r.status)==="ยกเลิก")return "ยกเลิก";if(out<=0.009)return "จ่ายครบแล้ว";if(num(r.paidAmount)>0)return "จ่ายบางส่วน";if(r.dueDate&&Date.parse(`${iso(r.dueDate)}T00:00:00Z`)<Date.now()-86400000)return "เกินกำหนด";return "รอจ่าย";}
function normalizeAp(payload={},existing={}){const ts=now(),gross=round2(payload.grossAmount??existing.grossAmount),vat=round2(payload.vatAmount??existing.vatAmount),subtotal=round2(payload.subtotal??existing.subtotal??(gross-vat)),whtRate=num(payload.whtRate??existing.whtRate),wht=round2(payload.whtAmount??existing.whtAmount??subtotal*whtRate/100),net=round2(payload.netPayable??existing.netPayable??(gross-wht)),paid=round2(payload.paidAmount??existing.paidAmount??0),settled=round2(payload.settledAmount??existing.settledAmount??((payload.outstanding!==undefined&&payload.outstanding!=="")?Math.max(0,gross-num(payload.outstanding)):0)),outstanding=Math.max(0,round2(gross-settled));const r={issueDate:iso(payload.issueDate||existing.issueDate||new Date()),dueDate:iso(payload.dueDate||existing.dueDate||payload.issueDate||new Date()),id:existing.id||id("AP"),supplierId:clean(payload.supplierId||existing.supplierId,80),supplier:clean(payload.supplier||existing.supplier,200),supplierTaxId:clean(payload.supplierTaxId||existing.supplierTaxId,30),documentType:clean(payload.documentType||existing.documentType||"ใบแจ้งหนี้",80),billNo:clean(payload.billNo||existing.billNo,120),taxInvoiceNo:clean(payload.taxInvoiceNo||existing.taxInvoiceNo,120),category:clean(payload.category||existing.category||"ค่าใช้จ่ายทั่วไป",120),description:clean(payload.description||existing.description,700),subtotal,vatAmount:vat,grossAmount:gross,whtRate,whtAmount:wht,netPayable:net,paidAmount:paid,settledAmount:settled,outstanding,paymentChannelId:clean(existing.paymentChannelId,120),attachmentUrl:clean(payload.attachmentUrl||existing.attachmentUrl,1000),note:clean(payload.note||existing.note,800),source:clean(payload.source||existing.source||"Dashboard",80),createdAt:existing.createdAt||ts,updatedAt:ts};r.status=apStatus({...r,status:payload.status||existing.status});return r;}
export async function getPayables(env,sheetId,token=null){const [rows,payments]=await Promise.all([list(env,sheetId,token,"ap"),list(env,sheetId,token,"apPayments")]);const today=iso(new Date());const active=rows.filter(x=>x.status!=="ยกเลิก");return {ok:true,rows:rows.map(r=>({...r,grossAmount:num(r.grossAmount),vatAmount:num(r.vatAmount),whtAmount:num(r.whtAmount),netPayable:num(r.netPayable),paidAmount:num(r.paidAmount),settledAmount:num(r.settledAmount),outstanding:num(r.outstanding),status:apStatus(r)})),payments,summary:{totalOutstanding:round2(active.reduce((s,r)=>s+num(r.outstanding),0)),overdue:round2(active.filter(r=>r.dueDate<today&&num(r.outstanding)>0).reduce((s,r)=>s+num(r.outstanding),0)),dueToday:round2(active.filter(r=>r.dueDate===today).reduce((s,r)=>s+num(r.outstanding),0)),count:active.length}};}
export async function createPayable(env,sheetId,payload={},token=null,actor="Dashboard"){await assertPeriodOpen(env,sheetId,payload.issueDate||new Date(),token);const rec=normalizeAp(payload);if(!rec.supplier)return {ok:false,error:"กรอกชื่อผู้ขาย/เจ้าหนี้"};if(!(rec.grossAmount>0))return {ok:false,error:"ยอดเจ้าหนี้ต้องมากกว่า 0"};if(!rec.supplierId){const c=await upsertContact(env,sheetId,{type:"ผู้ขาย/เจ้าหนี้",name:rec.supplier,taxId:rec.supplierTaxId,source:"Auto AP"},token,actor).catch(()=>null);if(c?.record?.id)rec.supplierId=c.record.id;}await append(env,sheetId,token,"ap",rec);await postPayableInvoiceJournal(env,sheetId,rec,token,actor).catch(e=>console.warn("ap journal",e.message));await writeAudit(env,sheetId,token,{actor,action:"CREATE_AP",entityType:"payable",entityId:rec.id,summary:`ตั้งเจ้าหนี้ ${rec.supplier} ${rec.grossAmount}`,after:rec});return {ok:true,record:rec};}
export async function updatePayable(env,sheetId,apId,patch={},token=null,actor="Dashboard"){const old=await findBy(env,sheetId,token,"ap","id",apId);if(!old)return {ok:false,error:"ไม่พบเจ้าหนี้"};await assertPeriodOpen(env,sheetId,patch.issueDate||old.issueDate,token);if(num(old.settledAmount)>0&&("grossAmount" in patch||"supplier" in patch))return {ok:false,error:"รายการนี้มีการจ่ายแล้ว แก้ยอด/ผู้ขายไม่ได้ ให้ยกเลิกหรือทำเอกสารปรับปรุงแทน"};const rec=normalizeAp(patch,old);const out=await patchRow(env,sheetId,token,"ap",old,rec);await writeAudit(env,sheetId,token,{actor,action:"UPDATE_AP",entityType:"payable",entityId:apId,summary:`แก้ไขเจ้าหนี้ ${rec.supplier}`,before:old,after:out});return {ok:true,record:out};}
export async function addPayablePayment(env,sheetId,apId,payment={},token=null,actor="Dashboard"){const old=await findBy(env,sheetId,token,"ap","id",apId);if(!old)return {ok:false,error:"ไม่พบเจ้าหนี้"};await assertPeriodOpen(env,sheetId,payment.paidDate||new Date(),token);const cash=round2(payment.cashAmount),wht=round2(payment.whtAmount),settled=round2(payment.settledAmount||cash+wht);if(!(settled>0))return {ok:false,error:"กรอกยอดจ่ายหรือยอดตัดเจ้าหนี้"};if(settled>num(old.outstanding)+0.01)return {ok:false,error:"ยอดตัดเจ้าหนี้เกินยอดคงค้าง"};const p={paymentId:id("APPAY"),apId,paidDate:iso(payment.paidDate||new Date()),cashAmount:cash,whtAmount:wht,settledAmount:settled,paymentChannelId:clean(payment.paymentChannelId,120),referenceNo:clean(payment.referenceNo,160),slipUrl:clean(payment.slipUrl,1000),note:clean(payment.note,500),createdAt:now()};await append(env,sheetId,token,"apPayments",p);const next={paidAmount:round2(num(old.paidAmount)+cash),settledAmount:round2(num(old.settledAmount)+settled),outstanding:Math.max(0,round2(num(old.grossAmount)-num(old.settledAmount)-settled)),paymentChannelId:p.paymentChannelId,updatedAt:now()};next.status=apStatus({...old,...next});await patchRow(env,sheetId,token,"ap",old,next);await postPayablePaymentJournal(env,sheetId,old,p,token,actor).catch(e=>console.warn("ap payment journal",e.message));await writeAudit(env,sheetId,token,{actor,action:"PAY_AP",entityType:"payable",entityId:apId,summary:`จ่ายเจ้าหนี้ ${old.supplier} เงินออก ${cash}`,before:old,after:{...old,...next,payment:p}});return {ok:true,payment:p,record:{...old,...next}};}


export async function getContactStatement(env,sheetId,query={},token=null){
  const contactId=clean(query.contactId||query.id,80),name=clean(query.name,200).toLowerCase(),taxId=clean(query.taxId,30);
  const [contacts,income,incomePayments,payables,apPayments]=await Promise.all([list(env,sheetId,token,"contacts"),listIncome(env,sheetId,token),listIncomePayments(env,sheetId,token),list(env,sheetId,token,"ap"),list(env,sheetId,token,"apPayments")]);
  const contact=contacts.find(c=>contactId&&c.id===contactId)||contacts.find(c=>taxId&&c.taxId===taxId)||contacts.find(c=>name&&String(c.name||"").toLowerCase()===name)||null;
  const match=(party,partyTax)=>{if(contact?.taxId&&partyTax&&String(partyTax)===String(contact.taxId))return true;const target=(contact?.name||query.name||"").trim().toLowerCase();return !!target&&String(party||"").trim().toLowerCase()===target;};
  const ar=income.filter(r=>match(r.customer,r.customerTaxId)),ap=payables.filter(r=>match(r.supplier,r.supplierTaxId));
  const arIds=new Set(ar.map(r=>r.id)),apIds=new Set(ap.map(r=>r.id));
  const receipts=incomePayments.filter(p=>arIds.has(p.incomeId)),payments=apPayments.filter(p=>apIds.has(p.apId));
  return {ok:true,contact:contact||{name:query.name||"คู่ค้า",taxId:query.taxId||""},receivables:ar,payables:ap,receipts,payments,summary:{receivableOutstanding:round2(ar.reduce((s,r)=>s+num(r.outstanding),0)),payableOutstanding:round2(ap.reduce((s,r)=>s+num(r.outstanding),0)),receivedCash:round2(receipts.reduce((s,r)=>s+num(r.cashAmount),0)),paidCash:round2(payments.reduce((s,r)=>s+num(r.cashAmount),0))}};
}
export async function getOpeningBalances(env,sheetId,token=null){const rows=await list(env,sheetId,token,"opening");return {ok:true,rows,summary:{debit:round2(rows.reduce((s,r)=>s+num(r.debit),0)),credit:round2(rows.reduce((s,r)=>s+num(r.credit),0))}};}
export async function addOpeningBalance(env,sheetId,p={},token=null,actor="Dashboard"){const rec={asOfDate:iso(p.asOfDate||new Date()),id:id("OPEN"),accountCode:clean(p.accountCode,30),accountName:clean(p.accountName,180),debit:round2(p.debit),credit:round2(p.credit),reference:clean(p.reference,160),note:clean(p.note,600),source:clean(p.source||"Migration",80),createdAt:now()};if(!rec.accountCode&&!rec.accountName)return {ok:false,error:"ระบุบัญชี"};if(rec.debit>0&&rec.credit>0)return {ok:false,error:"หนึ่งบรรทัดใส่ได้เดบิตหรือเครดิตอย่างใดอย่างหนึ่ง"};await append(env,sheetId,token,"opening",rec);await writeAudit(env,sheetId,token,{actor,action:"ADD_OPENING",entityType:"opening",entityId:rec.id,summary:`ยอดยกมา ${rec.accountCode} ${rec.accountName}`,after:rec});return {ok:true,record:rec};}

export async function importMigration(env,sheetId,payload={},token=null,actor="Dashboard"){
  const type=clean(payload.type,40),rows=Array.isArray(payload.rows)?payload.rows.slice(0,10000):[],batchId=id("MIG"),errors=[];let records=[];
  await ensureAccountingSuiteTabs(env,sheetId,token);
  if(type==="receivables"){
    let success=0;
    for(let i=0;i<rows.length;i++){const r=rows[i]||{};try{const gross=round2(r.grossAmount||r.amount),vat=round2(r.vatAmount),base=Math.max(0,gross-vat),vatRate=base>0?round2(vat/base*100):0,outstanding=Math.max(0,round2(r.outstanding===""||r.outstanding==null?gross:r.outstanding)),settled=Math.max(0,round2(gross-outstanding));const out=await createIncome(env,sheetId,{issueDate:r.issueDate||r.date,dueDate:r.dueDate||"",customer:r.customer||r.party||"ลูกค้าเดิม",customerTaxId:r.customerTaxId||r.taxId||"",category:r.category||"รายได้อื่น",description:r.description||"ยอดลูกหนี้ยกมา",documentType:r.documentType||"ใบแจ้งหนี้",invoiceNo:r.invoiceNo||r.docNo||"",taxInvoiceNo:r.taxInvoiceNo||"",amount:gross,priceMode:vat>0?"inclusive":"no_vat",vatRate,source:`Migration:${clean(payload.fileName,120)}`,initialPayment:settled>0?{cashAmount:settled,whtAmount:0,receivedDate:r.lastReceivedDate||r.issueDate||new Date(),source:"Migration opening settlement"}:undefined},token);if(!out.ok)throw new Error(out.message||out.reason||"นำเข้าลูกหนี้ไม่สำเร็จ");success++;}catch(e){if(errors.length<100)errors.push({row:i+1,error:e.message});}}
    const result={importedAt:now(),batchId,type,fileName:clean(payload.fileName,240),total:rows.length,success,failed:rows.length-success,status:rows.length===success?"สำเร็จ":success?"สำเร็จบางส่วน":"ไม่สำเร็จ",notes:errors.length?JSON.stringify(errors).slice(0,45000):""};await append(env,sheetId,token,"migration",result);await writeAudit(env,sheetId,token,{actor,action:"MIGRATION_IMPORT",entityType:"migration",entityId:batchId,summary:`นำเข้าลูกหนี้ ${success}/${rows.length} รายการ`,after:result});return {ok:true,...result,errors};
  }
  for(let i=0;i<rows.length;i++){
    const r=rows[i]||{};
    try{
      if(type==="contacts"){
        const name=clean(r.name,200);if(!name)throw new Error("ไม่มีชื่อคู่ค้า");records.push({id:id("CON"),type:clean(r.type||"ทั้งสอง",30),name,taxId:clean(r.taxId,30),branch:clean(r.branch||"สำนักงานใหญ่",100),email:clean(r.email,180),phone:clean(r.phone,60),address:clean(r.address,800),paymentTerms:Math.max(0,Math.min(365,num(r.paymentTerms))),defaultWhtRate:Math.max(0,Math.min(100,num(r.defaultWhtRate))),vatRegistered:"TRUE",active:"TRUE",source:`Migration:${clean(payload.fileName,120)}`,createdAt:now(),updatedAt:now()});
      }else if(type==="payables"){
        const rec=normalizeAp({...r,source:`Migration:${clean(payload.fileName,120)}`});if(!rec.supplier)throw new Error("ไม่มีชื่อผู้ขาย");if(!(rec.grossAmount>0))throw new Error("ยอดต้องมากกว่า 0");records.push(rec);
      }else if(type==="opening"){
        const rec={asOfDate:iso(r.asOfDate||new Date()),id:id("OPEN"),accountCode:clean(r.accountCode,30),accountName:clean(r.accountName,180),debit:round2(r.debit),credit:round2(r.credit),reference:clean(r.reference,160),note:clean(r.note,600),source:`Migration:${clean(payload.fileName,120)}`,createdAt:now()};if(!rec.accountCode&&!rec.accountName)throw new Error("ไม่มีบัญชี");if(rec.debit>0&&rec.credit>0)throw new Error("เดบิตและเครดิตอยู่บรรทัดเดียวกันไม่ได้");records.push(rec);
      }else if(type==="archive"){
        records.push({transactionDate:iso(r.transactionDate||r.date||new Date()),id:id("ARC"),direction:clean(r.direction||r.type||"ข้อมูลย้อนหลัง",40),docNo:clean(r.docNo||r.invoiceNo||r.reference,160),party:clean(r.party||r.vendor||r.customer,200),description:clean(r.description||r.note,800),amount:round2(r.amount),vat:round2(r.vat),wht:round2(r.wht),status:clean(r.status||"ประวัติ",80),sourceSystem:clean(payload.sourceSystem||r.sourceSystem||"ระบบเดิม",120),sourceRef:clean(r.sourceRef||r.id,180),attachmentUrl:clean(r.attachmentUrl||r.url,1000),rawJson:JSON.stringify(r).slice(0,45000),importBatchId:batchId,createdAt:now()});
      }else throw new Error("migration_type_not_supported");
    }catch(e){if(errors.length<100)errors.push({row:i+1,error:e.message});}
  }
  const key={contacts:"contacts",payables:"ap",opening:"opening",archive:"archive"}[type];
  if(type==="contacts"&&records.length){const existing=await list(env,sheetId,token,"contacts"),seen=new Set(existing.map(x=>(clean(x.taxId)||clean(x.name).toLowerCase())).filter(Boolean));records=records.filter((r,i)=>{const k=clean(r.taxId)||clean(r.name).toLowerCase();if(k&&seen.has(k)){if(errors.length<100)errors.push({row:i+1,error:"คู่ค้านี้มีอยู่แล้ว"});return false}if(k)seen.add(k);return true});}
  if(type==="payables"&&records.length){const existing=await list(env,sheetId,token,"ap"),seen=new Set(existing.map(x=>`${clean(x.supplierTaxId||x.supplier).toLowerCase()}|${clean(x.billNo||x.taxInvoiceNo)}`).filter(x=>!x.endsWith("|")));records=records.filter((r,i)=>{const k=`${clean(r.supplierTaxId||r.supplier).toLowerCase()}|${clean(r.billNo||r.taxInvoiceNo)}`;if(!k.endsWith("|")&&seen.has(k)){if(errors.length<100)errors.push({row:i+1,error:"เลขบิล/คู่ค้านี้มีอยู่แล้ว"});return false}if(!k.endsWith("|"))seen.add(k);return true});}
  if(key&&records.length)await appendMany(env,sheetId,token,key,records);
  const success=records.length,result={importedAt:now(),batchId,type,fileName:clean(payload.fileName,240),total:rows.length,success,failed:rows.length-success,status:rows.length===success?"สำเร็จ":success?"สำเร็จบางส่วน":"ไม่สำเร็จ",notes:errors.length?JSON.stringify(errors).slice(0,45000):""};
  await append(env,sheetId,token,"migration",result);await writeAudit(env,sheetId,token,{actor,action:"MIGRATION_IMPORT",entityType:"migration",entityId:batchId,summary:`นำเข้า ${type} ${success}/${rows.length} รายการ`,after:result});return {ok:true,...result,errors};
}
export async function getMigrationDashboard(env,sheetId,token=null){const [imports,archiveRows,opening,contactRows,payableRows]=await Promise.all([list(env,sheetId,token,"migration"),countRows(env,sheetId,token,"archive"),list(env,sheetId,token,"opening"),countRows(env,sheetId,token,"contacts"),countRows(env,sheetId,token,"ap")]);const openingDebit=round2(opening.reduce((s,r)=>s+num(r.debit),0)),openingCredit=round2(opening.reduce((s,r)=>s+num(r.credit),0));return {ok:true,imports:imports.slice(0,50),summary:{archiveRows,openingRows:opening.length,contactRows,payableRows,openingDebit,openingCredit,openingBalanced:Math.abs(openingDebit-openingCredit)<=0.01,lastImport:imports[0]||null}};}

async function closeChecklist(env,sheetId,period,token){
  const [expenses,income,payables,reconOut,reconIn]=await Promise.all([
    readExpenses(env,sheetId,token),listIncome(env,sheetId,token),getPayables(env,sheetId,token),getReconciliationDashboard(env,sheetId,token).catch(()=>({rows:[]})),listIncomeReconciliationRows(env,sheetId,token).catch(()=>[])
  ]);
  const exp=expenses.filter(r=>month(r.dateISO||r.dateText)===period),inc=income.filter(r=>month(r.issueDate)===period),aps=(payables.rows||[]).filter(r=>month(r.issueDate)===period);
  const expPending=exp.filter(r=>!["จ่ายแล้ว","ลบแล้ว"].includes(String(r.status||""))&&String(r.paid||"").toUpperCase()!=="TRUE").length;
  const missingDocs=exp.filter(r=>!r.imageUrl&&!r.attReceipt&&!r.attTax&&!r.attOther).length;
  const outUnmatched=(reconOut.rows||[]).filter(r=>month(r.transactionDate)===period&&!['กระทบยอดแล้ว','ข้าม'].includes(String(r.displayStatus||r.status||""))).length;
  const inUnmatched=(reconIn||[]).filter(r=>month(r.transactionDate)===period&&!['กระทบยอดแล้ว','ข้าม'].includes(String(r.status||""))).length;
  const apOpen=aps.filter(r=>num(r.outstanding)>0).length;
  const checks=[
    {key:"expense_review",label:"รายจ่ายค้างดำเนินการ",count:expPending,blocking:expPending>0},
    {key:"expense_docs",label:"รายจ่ายขาดเอกสาร",count:missingDocs,blocking:missingDocs>0},
    {key:"bank_out",label:"เงินออกยังไม่กระทบยอด",count:outUnmatched,blocking:outUnmatched>0},
    {key:"bank_in",label:"เงินเข้ายังไม่กระทบยอด",count:inUnmatched,blocking:inUnmatched>0},
    {key:"ap_open",label:"เจ้าหนี้คงค้างในงวด",count:apOpen,blocking:false},
    {key:"income_open",label:"ลูกหนี้คงค้างในงวด",count:inc.filter(r=>num(r.outstanding)>0).length,blocking:false},
  ];
  return {period,checks,blocking:checks.filter(x=>x.blocking).reduce((s,x)=>s+x.count,0),expenseCount:exp.length,incomeCount:inc.length,apCount:aps.length};
}
export async function getPeriodDashboard(env,sheetId,period,token=null){const p=period||month(new Date());const [rows,check]=await Promise.all([list(env,sheetId,token,"periods"),closeChecklist(env,sheetId,p,token)]);const current=rows.find(x=>x.period===p)||null;return {ok:true,current,period:p,check,history:rows.slice(0,24)};}
export async function closePeriod(env,sheetId,period,opts={},token=null,actor="Dashboard"){
  const p=/^\d{4}-\d{2}$/.test(period)?period:month(new Date());const check=await closeChecklist(env,sheetId,p,token);if(check.blocking>0&&!opts.force)return {ok:false,error:"close_blocked",message:"ยังมีงานที่ต้องจัดการก่อนปิดงวด",check};
  const old=await findBy(env,sheetId,token,"periods","period",p);const rec={period:p,status:"ปิดงวด",closedAt:now(),closedBy:clean(actor,120),reopenedAt:old?.reopenedAt||"",reopenedBy:old?.reopenedBy||"",reason:clean(opts.reason,500),checklistJson:JSON.stringify(check)};if(old)await patchRow(env,sheetId,token,"periods",old,rec);else await append(env,sheetId,token,"periods",rec);await writeAudit(env,sheetId,token,{actor,action:"CLOSE_PERIOD",entityType:"period",entityId:p,summary:`ปิดงวด ${p}${opts.force?" (บังคับ)":""}`,before:old,after:rec});return {ok:true,record:rec,check};
}
export async function reopenPeriod(env,sheetId,period,reason,token=null,actor="Dashboard"){if(!clean(reason))return {ok:false,error:"กรุณาระบุเหตุผลที่เปิดงวดใหม่"};const old=await findBy(env,sheetId,token,"periods","period",period);if(!old||old.status!=="ปิดงวด")return {ok:false,error:"งวดนี้ยังไม่ได้ปิด"};const patch={status:"เปิดใหม่",reopenedAt:now(),reopenedBy:clean(actor,120),reason:clean(reason,800)};await patchRow(env,sheetId,token,"periods",old,patch);await writeAudit(env,sheetId,token,{actor,action:"REOPEN_PERIOD",entityType:"period",entityId:period,summary:`เปิดงวด ${period} ใหม่: ${reason}`,before:old,after:{...old,...patch}});return {ok:true,record:{...old,...patch}};}

export async function getTaxCenter(env,sheetId,period,token=null){const p=period||month(new Date());const [expenses,income,payments,aps,apPays]=await Promise.all([readExpenses(env,sheetId,token),listIncome(env,sheetId,token),listIncomePayments(env,sheetId,token),list(env,sheetId,token,"ap"),list(env,sheetId,token,"apPayments")]);const exp=expenses.filter(r=>month(r.dateISO||r.dateText)===p),inc=income.filter(r=>month(r.issueDate)===p),ip=payments.filter(r=>month(r.receivedDate)===p),ap=aps.filter(r=>month(r.issueDate)===p),app=apPays.filter(r=>month(r.paidDate)===p);const inputVatRows=[...exp.filter(r=>num(r.vat)>0).map(r=>({date:r.dateISO||r.dateText,party:r.vendor||"",docNo:r.slipNo||"",base:round2(num(r.amount)-num(r.vat)),vat:round2(r.vat),amount:round2(r.amount),source:"รายจ่าย"})),...ap.filter(r=>num(r.vatAmount)>0).map(r=>({date:r.issueDate,party:r.supplier||"",docNo:r.taxInvoiceNo||r.billNo||"",base:round2(r.subtotal),vat:round2(r.vatAmount),amount:round2(r.grossAmount),source:"เจ้าหนี้"}))];const outputVatRows=inc.filter(r=>num(r.vatAmount)>0).map(r=>({date:r.issueDate,party:r.customer||"",docNo:r.taxInvoiceNo||r.invoiceNo||r.receiptNo||"",base:round2(r.subtotal),vat:round2(r.vatAmount),amount:round2(r.grossAmount)}));const whtCreditRows=ip.filter(r=>num(r.whtAmount)>0).map(r=>({date:r.receivedDate,incomeId:r.incomeId,amount:round2(r.whtAmount),reference:r.referenceNo||"",certificateUrl:r.whtCertificateUrl||""}));const whtPayableRows=app.filter(r=>num(r.whtAmount)>0).map(r=>({date:r.paidDate,apId:r.apId,amount:round2(r.whtAmount),reference:r.referenceNo||""}));const inputVat=round2(inputVatRows.reduce((s,r)=>s+r.vat,0)),outputVat=round2(outputVatRows.reduce((s,r)=>s+r.vat,0)),whtCredit=round2(whtCreditRows.reduce((s,r)=>s+r.amount,0)),whtPayable=round2(whtPayableRows.reduce((s,r)=>s+r.amount,0));const warnings=[];exp.filter(r=>num(r.vat)>0&&!r.attTax).slice(0,25).forEach(r=>warnings.push({type:"vat_input_doc",id:r.id,label:`${r.vendor||"รายจ่าย"} มี VAT แต่ยังไม่พบใบกำกับภาษี`,amount:num(r.amount)}));inc.filter(r=>num(r.vatAmount)>0&&!r.taxInvoiceNo).slice(0,25).forEach(r=>warnings.push({type:"vat_output_no",id:r.id,label:`${r.customer||"รายรับ"} มี VAT แต่ยังไม่มีเลขใบกำกับภาษี`,amount:num(r.grossAmount)}));ip.filter(r=>num(r.whtAmount)>0&&!r.whtCertificateUrl).slice(0,25).forEach(r=>warnings.push({type:"wht_certificate",id:r.paymentId,label:`รับ WHT ${r.whtAmount} บาท แต่ยังไม่มีหนังสือรับรอง 50 ทวิ`,amount:num(r.whtAmount)}));return {ok:true,period:p,summary:{inputVat,outputVat,vatDifference:round2(outputVat-inputVat),whtCredit,whtPayable},warnings,counts:{expenses:exp.length,income:inc.length,ap:ap.length,incomePayments:ip.length,apPayments:app.length},inputVatRows,outputVatRows,whtCreditRows,whtPayableRows,note:"ข้อมูลช่วยตรวจสอบและเตรียมงานภาษี ไม่ใช่การยื่นแบบอัตโนมัติ"};}

export async function getAudit(env,sheetId,token=null,{limit=300}={}){const rows=await list(env,sheetId,token,"audit");return {ok:true,rows:rows.slice(0,Math.max(1,Math.min(1000,Number(limit)||300)))};}

function journalDedupKey(sheetId,sourceType,sourceId,reference=""){const part=v=>encodeURIComponent(String(v||"")).slice(0,180);return `journal:v7:${part(sheetId)}:${part(sourceType)}:${part(sourceId)}:${part(reference)}`;}
async function journalExists(env,sheetId,token,sourceType,sourceId,reference){const key=journalDedupKey(sheetId,sourceType,sourceId,reference);if(env.KV&&await env.KV.get(key).catch(()=>null)==="1")return true;const rows=await list(env,sheetId,token,"journal");const found=rows.some(r=>r.sourceType===sourceType&&r.sourceId===sourceId&&(!reference||r.reference===reference));if(found&&env.KV)await env.KV.put(key,"1").catch(()=>{});return found;}
export async function postJournal(env,sheetId,{date,reference,description,sourceType,sourceId,lines,actor="System"},token=null){if(!Array.isArray(lines)||lines.length<2)return {ok:false,error:"journal_lines"};await assertPeriodOpen(env,sheetId,date,token);const dedupKey=journalDedupKey(sheetId,sourceType,sourceId,reference);if(await journalExists(env,sheetId,token,sourceType,sourceId,reference))return {ok:true,duplicate:true};const debit=round2(lines.reduce((s,x)=>s+num(x.debit),0)),credit=round2(lines.reduce((s,x)=>s+num(x.credit),0));if(Math.abs(debit-credit)>.01)return {ok:false,error:"journal_unbalanced",debit,credit};const jid=id("JV"),ts=now(),rows=lines.map(line=>({date:iso(date),journalId:jid,reference:clean(reference,160),description:clean(description,500),accountCode:clean(line.accountCode,30),accountName:clean(line.accountName,180),debit:round2(line.debit),credit:round2(line.credit),sourceType:clean(sourceType,80),sourceId:clean(sourceId,120),createdAt:ts,postedBy:clean(actor,120)}));await appendMany(env,sheetId,token,"journal",rows);if(env.KV)await env.KV.put(dedupKey,"1").catch(()=>{});return {ok:true,journalId:jid,debit,credit};}
export async function postExpenseJournal(env,sheetId,expense,token=null,actor="LINE"){const gross=round2(expense.amount),vat=Math.max(0,round2(expense.vat)),base=Math.max(0,round2(gross-vat));if(!(gross>0))return {ok:false,error:"no_amount"};return postJournal(env,sheetId,{date:expense.dateISO||expense.dateText||expense.date,reference:expense.slipNo||expense.id,description:`รายจ่าย ${expense.vendor||""}`,sourceType:"expense",sourceId:expense.id,actor,lines:[{accountCode:"5000",accountName:"ค่าใช้จ่ายดำเนินงาน",debit:base},{accountCode:"1190",accountName:"ภาษีซื้อ",debit:vat},{accountCode:"2050",accountName:"เจ้าหนี้พนักงาน/ค่าใช้จ่ายค้างจ่าย",credit:gross}]},token);}
export async function postIncomeInvoiceJournal(env,sheetId,inc,token=null,actor="System"){const gross=round2(inc.grossAmount),vat=round2(inc.vatAmount),base=Math.max(0,round2(gross-vat));if(!(gross>0))return {ok:false,error:"no_amount"};return postJournal(env,sheetId,{date:inc.issueDate,reference:inc.invoiceNo||inc.taxInvoiceNo||inc.id,description:`รายรับ ${inc.customer||""}`,sourceType:"income",sourceId:inc.id,actor,lines:[{accountCode:"1100",accountName:"ลูกหนี้การค้า",debit:gross},{accountCode:"4000",accountName:"รายได้จากการขายและบริการ",credit:base},{accountCode:"2190",accountName:"ภาษีขาย",credit:vat}]},token);}
export async function postIncomePaymentJournal(env,sheetId,payment,token=null,actor="System"){const settled=round2(payment.settledAmount),cash=round2(payment.cashAmount),wht=round2(payment.whtAmount);return postJournal(env,sheetId,{date:payment.receivedDate,reference:payment.referenceNo||payment.paymentId,description:"รับชำระลูกหนี้",sourceType:"income_payment",sourceId:payment.paymentId,actor,lines:[{accountCode:"1000",accountName:"เงินสดและธนาคาร",debit:cash},{accountCode:"1150",accountName:"ภาษีหัก ณ ที่จ่ายรอรับ",debit:wht},{accountCode:"1100",accountName:"ลูกหนี้การค้า",credit:settled}]},token);}
export async function postReimbursementPaymentJournal(env,sheetId,batch,token=null,actor="Dashboard"){const amount=round2(batch?.total||batch?.amount);if(!(amount>0))return {ok:false,error:"no_amount"};const batchId=clean(batch?.id||batch?.batchId||batch?.docId,120);return postJournal(env,sheetId,{date:batch?.paidAt||new Date(),reference:batch?.docId||batchId,description:`จ่ายคืนผู้เบิก ${batch?.payerName||batch?.displayName||""}`,sourceType:"reimbursement_payment",sourceId:batchId,actor,lines:[{accountCode:"2050",accountName:"เจ้าหนี้พนักงาน/ค่าใช้จ่ายค้างจ่าย",debit:amount},{accountCode:"1000",accountName:"เงินสดและธนาคาร",credit:amount}]},token);}
async function postPayableInvoiceJournal(env,sheetId,ap,token,actor){const gross=round2(ap.grossAmount),vat=round2(ap.vatAmount),base=Math.max(0,round2(gross-vat));return postJournal(env,sheetId,{date:ap.issueDate,reference:ap.billNo||ap.taxInvoiceNo||ap.id,description:`ตั้งเจ้าหนี้ ${ap.supplier}`,sourceType:"ap",sourceId:ap.id,actor,lines:[{accountCode:"5000",accountName:"ค่าใช้จ่ายดำเนินงาน",debit:base},{accountCode:"1190",accountName:"ภาษีซื้อ",debit:vat},{accountCode:"2000",accountName:"เจ้าหนี้การค้า",credit:gross}]},token);}
async function postPayablePaymentJournal(env,sheetId,ap,p,token,actor){return postJournal(env,sheetId,{date:p.paidDate,reference:p.referenceNo||p.paymentId,description:`จ่ายเจ้าหนี้ ${ap.supplier}`,sourceType:"ap_payment",sourceId:p.paymentId,actor,lines:[{accountCode:"2000",accountName:"เจ้าหนี้การค้า",debit:p.settledAmount},{accountCode:"1000",accountName:"เงินสดและธนาคาร",credit:p.cashAmount},{accountCode:"2150",accountName:"ภาษีหัก ณ ที่จ่ายค้างจ่าย",credit:p.whtAmount}]},token);}
export async function getLedger(env,sheetId,token=null,{from="",to=""}={}){const [coa,journals,opening]=await Promise.all([list(env,sheetId,token,"coa",{reverse:false}),list(env,sheetId,token,"journal",{reverse:false}),list(env,sheetId,token,"opening",{reverse:false})]);const filtered=journals.filter(r=>(!from||r.date>=from)&&(!to||r.date<=to));const tb=new Map();const add=(code,name,d,c)=>{const x=tb.get(code)||{accountCode:code,accountName:name,debit:0,credit:0};x.debit+=num(d);x.credit+=num(c);tb.set(code,x);};opening.forEach(r=>add(r.accountCode,r.accountName,r.debit,r.credit));filtered.forEach(r=>add(r.accountCode,r.accountName,r.debit,r.credit));const trial=[...tb.values()].map(x=>({...x,debit:round2(x.debit),credit:round2(x.credit),balance:round2(x.debit-x.credit)})).sort((a,b)=>String(a.accountCode).localeCompare(String(b.accountCode)));return {ok:true,coa,journals:filtered.slice(-1000).reverse(),trialBalance:trial,summary:{debit:round2(trial.reduce((s,x)=>s+x.debit,0)),credit:round2(trial.reduce((s,x)=>s+x.credit,0))}};}

export async function getTodayWork(env,sheetId,token=null){const today=iso(new Date()),thisMonth=today.slice(0,7);const [expenses,income,payables,periodRows]=await Promise.all([readExpenses(env,sheetId,token),listIncome(env,sheetId,token),getPayables(env,sheetId,token),list(env,sheetId,token,"periods").catch(()=>[])]);const pendingExp=expenses.filter(r=>!["จ่ายแล้ว","ลบแล้ว"].includes(String(r.status||""))&&String(r.paid||"").toUpperCase()!=="TRUE");const overdueIncome=income.filter(r=>r.dueDate&&r.dueDate<today&&num(r.outstanding)>0);const overdueAp=(payables.rows||[]).filter(r=>r.dueDate&&r.dueDate<today&&num(r.outstanding)>0);const dueAp=(payables.rows||[]).filter(r=>r.dueDate===today&&num(r.outstanding)>0);const currentPeriod=(periodRows||[]).find(r=>r.period===thisMonth)||null;const tasks=[{key:"expenses",label:"รายจ่ายรอดำเนินการ",count:pendingExp.length,amount:round2(pendingExp.reduce((s,r)=>s+num(r.amount),0)),severity:pendingExp.length?"warn":"ok",page:"expenses"},{key:"income",label:"ลูกหนี้เกินกำหนด",count:overdueIncome.length,amount:round2(overdueIncome.reduce((s,r)=>s+num(r.outstanding),0)),severity:overdueIncome.length?"bad":"ok",page:"income"},{key:"ap",label:"เจ้าหนี้ครบกำหนดวันนี้",count:dueAp.length,amount:round2(dueAp.reduce((s,r)=>s+num(r.outstanding),0)),severity:dueAp.length?"warn":"ok",page:"payables"},{key:"ap_overdue",label:"เจ้าหนี้เกินกำหนด",count:overdueAp.length,amount:round2(overdueAp.reduce((s,r)=>s+num(r.outstanding),0)),severity:overdueAp.length?"bad":"ok",page:"payables"}];return {ok:true,date:today,tasks,period:{period:thisMonth,closed:currentPeriod?.status==="ปิดงวด"}};}

export async function searchAccounting(env,sheetId,token=null,{q="",limit=80}={}){const needle=clean(q,160).toLowerCase();if(needle.length<2)return {ok:true,q:needle,rows:[]};const max=Math.max(10,Math.min(200,Number(limit)||80));const [expenses,income,contacts,ap,archive]=await Promise.all([readExpenses(env,sheetId,token),listIncome(env,sheetId,token),list(env,sheetId,token,"contacts"),list(env,sheetId,token,"ap"),list(env,sheetId,token,"archive")]);const hit=(values=[])=>values.some(v=>String(v??"").toLowerCase().includes(needle));const rows=[];for(const r of expenses){if(hit([r.id,r.vendor,r.transferor,r.payerName,r.note,r.category,r.amount,r.slipNo]))rows.push({type:"รายจ่าย",id:r.id,date:r.dateISO||r.dateText,title:r.vendor||r.note||"รายจ่าย",detail:[r.category,r.payerName,r.status].filter(Boolean).join(" · "),amount:round2(r.amount),page:"expenses"});}for(const r of income){if(hit([r.id,r.customer,r.customerTaxId,r.invoiceNo,r.taxInvoiceNo,r.receiptNo,r.description,r.grossAmount,r.outstanding]))rows.push({type:"รายรับ/ลูกหนี้",id:r.id,date:r.issueDate,title:r.customer||r.invoiceNo||"รายรับ",detail:[r.invoiceNo,r.status,r.customerTaxId].filter(Boolean).join(" · "),amount:round2(r.grossAmount),page:"income"});}for(const r of ap){if(hit([r.id,r.supplier,r.supplierTaxId,r.billNo,r.taxInvoiceNo,r.description,r.grossAmount,r.outstanding]))rows.push({type:"เจ้าหนี้",id:r.id,date:r.issueDate,title:r.supplier||r.billNo||"เจ้าหนี้",detail:[r.billNo,r.status,r.supplierTaxId].filter(Boolean).join(" · "),amount:round2(r.grossAmount),page:"payables"});}for(const r of contacts){if(hit([r.id,r.name,r.taxId,r.email,r.phone,r.address]))rows.push({type:"คู่ค้า",id:r.id,date:r.updatedAt||r.createdAt,title:r.name,detail:[r.type,r.taxId,r.phone].filter(Boolean).join(" · "),amount:0,page:"contacts"});}for(const r of archive){if(hit([r.id,r.docNo,r.party,r.description,r.amount,r.sourceRef,r.sourceSystem]))rows.push({type:"ประวัติเดิม",id:r.id,date:r.transactionDate,title:r.party||r.docNo||"ประวัติเดิม",detail:[r.docNo,r.description,r.sourceSystem].filter(Boolean).join(" · "),amount:round2(r.amount),page:"search",archive:true});}rows.sort((a,b)=>String(b.date||"").localeCompare(String(a.date||"")));return {ok:true,q:needle,total:rows.length,rows:rows.slice(0,max)};}

export async function getBackup(env,sheetId,token=null){const settings=await readSettings(env,sheetId,token).catch(()=>({}));const [expenses,income,incomePayments,contacts,ap,apPayments,opening,periods,archive,migration,audit,coa,journal,reconciliation]=await Promise.all([readExpenses(env,sheetId,token),listIncome(env,sheetId,token),listIncomePayments(env,sheetId,token),list(env,sheetId,token,"contacts"),list(env,sheetId,token,"ap"),list(env,sheetId,token,"apPayments"),list(env,sheetId,token,"opening"),list(env,sheetId,token,"periods"),list(env,sheetId,token,"archive"),list(env,sheetId,token,"migration"),list(env,sheetId,token,"audit"),list(env,sheetId,token,"coa"),list(env,sheetId,token,"journal"),getReconciliationDashboard(env,sheetId,token).catch(()=>({rows:[]}))]);return {ok:true,version:ACCOUNTING_SUITE_VERSION,exportedAt:now(),settings,financial:{expenses,income,incomePayments,reconciliation:reconciliation.rows||[]},accounting:{contacts,ap,apPayments,opening,periods,archive,migration,audit,coa,journal},note:"Full JSON export สำหรับสำรองและตรวจสอบข้อมูล ไม่ลบหรือเขียนทับข้อมูลต้นฉบับใน Google Sheet"};}
